# Generated by Django 5.2 on 2025-05-24 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_techniciannotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationassignment',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_assignments', to='services.appointment'),
        ),
    ]
