# Generated by Django 5.2 on 2025-05-24 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_verificationassignment_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='techniciannotification',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.appointment'),
        ),
    ]
