# Generated by Django 5.2 on 2025-05-25 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_techniciannotification_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationassignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
