# Generated by Django 5.2 on 2025-05-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_verificationassignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationassignment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
