# Generated by Django 5.2 on 2025-05-25 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_adminnotification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotification',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.appointment'),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='verificationassignment',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.appointment'),
        ),
    ]
