# Generated by Django 5.2 on 2025-05-26 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_galleryimage_delete_adminnotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
