# Generated by Django 5.2 on 2025-05-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='gallery_images/')),
                ('category', models.CharField(choices=[('general', 'General Pest Control'), ('spot', 'Termite Spot Treatment'), ('comprehensive', 'Termite Comprehensive')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
