# Generated by Django 5.2 on 2025-05-26 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_galleryimage_delete_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
