# Generated by Django 5.0.3 on 2025-05-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_galleryimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryImage',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('General Pest Control', 'General Pest Control'), ('Termite Spot Treatment', 'Termite Spot Treatment'), ('Termite Comprehensive]', 'Termite Comprehensive')], max_length=50),
        ),
    ]
