# Generated by Django 5.0.3 on 2025-05-29 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_delete_galleryimage_alter_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
