# Generated by Django 5.2 on 2025-06-01 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
