# Generated by Django 5.2 on 2025-06-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
