# Generated by Django 5.0.3 on 2025-09-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_photodocumentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
