# Generated by Django 5.0.3 on 2025-09-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0028_uploadedphoto_delete_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedphoto',
            name='category',
            field=models.CharField(choices=[('general', 'General Pest Control'), ('termite_comprehensive', 'Termite Comprehensive'), ('termite_spot', 'Termite Spot Treatment')], default='general', max_length=50),
        ),
    ]
