# Generated by Django 5.0.3 on 2025-09-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0029_uploadedphoto_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
