# Generated by Django 5.0.3 on 2025-09-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0030_appointment_estimated_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verificationassignment',
            old_name='status',
            new_name='approval_status',
        ),
        migrations.AddField(
            model_name='verificationassignment',
            name='progress_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
