# Generated by Django 5.0.3 on 2025-09-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0031_rename_status_verificationassignment_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
