# Generated by Django 5.0.3 on 2025-09-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0032_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='land_use_category',
            field=models.CharField(choices=[('Industrial', 'Industrial'), ('Residential', 'Residential'), ('Institutional', 'Institutional'), ('Commercial', 'Commercial')], default='Residential', max_length=50),
        ),
    ]
