# Generated by Django 5.0.3 on 2025-11-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0036_appointment_receipt_appointment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
