# Generated by Django 5.0.3 on 2025-11-13 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0037_receipt_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='archived',
        ),
    ]
