# Generated by Django 5.0.3 on 2025-11-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0038_remove_receipt_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationassignment',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved')], default='pending', max_length=10),
        ),
    ]
