# Generated by Django 5.0.3 on 2025-11-16 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0039_alter_verificationassignment_approval_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='technician_progress/')),
                ('description', models.TextField()),
                ('progress_status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.verificationassignment')),
            ],
        ),
    ]
