# Generated by Django 5.0.3 on 2025-11-17 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0041_customernotification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customernotification',
            old_name='customer',
            new_name='client_name',
        ),
    ]
