# Generated by Django 5.0.3 on 2025-11-17 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0042_rename_customer_customernotification_client_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customernotification',
            old_name='client_name',
            new_name='customer',
        ),
    ]
