# Generated by Django 5.0.3 on 2025-11-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0043_rename_client_name_customernotification_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customernotification',
            name='customer',
        ),
        migrations.AddField(
            model_name='customernotification',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
