# Generated by Django 5.0.3 on 2025-11-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0044_remove_customernotification_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='measurement',
            field=models.CharField(choices=[('ml', 'Milliliter (ml)'), ('L', 'Liters (L)')], default='ml', max_length=10),
        ),
    ]
