# Generated by Django 5.0.3 on 2025-11-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0045_product_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='measurement',
            field=models.CharField(blank=True, choices=[('ml', 'Milliliter (ml)'), ('L', 'Liters (L)')], max_length=10, null=True),
        ),
    ]
