# Generated by Django 5.0.3 on 2025-11-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0046_alter_product_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('General Pest Control', 'General Pest Control'), ('Termite Spot Treatment', 'Termite Spot Treatment'), ('Termite Comprehensive', 'Termite Comprehensive'), ('Materials', 'Materials'), ('Equipment', 'Equipment')], max_length=50),
        ),
    ]
