# Generated by Django 5.0.3 on 2025-11-20 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0048_technicianstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='measurement',
            field=models.CharField(blank=True, default='L', max_length=10, null=True),
        ),
    ]
