# Generated by Django 5.0.3 on 2025-11-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0049_alter_product_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='measurement',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
