# Generated by Django 5.0.3 on 2025-11-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0050_alter_product_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Materials', 'Materials'), ('Equipment', 'Equipment')], max_length=50),
        ),
    ]
