# Generated by Django 5.0.3 on 2025-11-20 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0051_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
    ]
