# Generated by Django 5.0.3 on 2025-11-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0052_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
