# Generated by Django 5.0.3 on 2025-11-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0053_product_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationassignment',
            name='inventory_updated',
            field=models.BooleanField(default=False),
        ),
    ]
